### ISSUE TITLE
Can't install on windows

### ISSUE THREAD

**Issue by FinagleLord** [matrach/matplotlib-terminal#1]
pip install isn't working, and I tried manually installing as well. Am I missing something? 

PS super dope project!!

**Comment by matrach** [comment]
Hi!
Thanks for your interest in the project! :D 
It seems that a dependency (*n2*) of my rendering lib is not supporting windows yet.

You can manually install https://github.com/matrach/img2unicode with commenting out the "n2" from the `setup.py` file, but
only the "_block_ renderers" (also called _dual renderers_) will work. You will have to use `plt.show('block')`

Also, if you're using standard Windows terminal, the rendering will look buggy due to a hacky ZERO LENGHT SPACE inserted after every character, in order to fix right-to-left handling by Gnome Terminal – in Windows' `cmd` it occupies a separate cell.
I was going to write some terminal detection to infer whether the RTL-sentinel should be emitted, but... I'm going to do that some day...

Anyway, you're welcome to send PR-s :)

**Comment by matrach** [comment]
Fixed in 0.1a4. Just update the package :).
